name: Continuos Integration
on:
    push:
    workflow_dispatch:

jobs:
    build:
      name: Build
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - uses: actions/setup-node@v3
          with:
            node-version: 20
  
        - name: install
          run: npm ci
        
        - name: eslint
          run: npm run lint
          
        - name: build
          run: npm run build
    test_unit:
      name: Unit Tests
      runs-on: ubuntu-latest
  
      steps:
        - uses: actions/checkout@v3
        - uses: actions/setup-node@v3
          with:
            node-version: 20
  
        - name: install
          run: npm ci
  
        - name: test
          run: npm run test
    test_visual:
      name: Visual
      timeout-minutes: 60
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - uses: actions/setup-node@v3
          with:
            node-version: 20
        - name: Install dependencies
          run: npm ci
        - name: Install Playwright Browsers
          run: npx playwright install --with-deps
        - name: Run Playwright tests
          run: npx playwright test
        - uses: actions/upload-artifact@v3
          if: always()
          with:
            name: playwright-report
            path: playwright-report/
            retention-days: 30
    publish:
      name: Publish
      timeout-minutes: 2
      runs-on: ubuntu-latest
      permissions: 
        contents: write
        pull-requests: write
      steps:
        - uses: google-github-actions/release-please-action@v4
          id: release
          with:
            # this assumes that you have created a personal access token
            # (PAT) and configured it as a GitHub action secret named
            # `MY_RELEASE_PLEASE_TOKEN` (this secret name is not important).
            token: ${{ secrets.GITHUB_TOKEN }}
            skip-github-pull-request: true
        - uses: actions/checkout@v4
          if: ${{ steps.release.outputs.release_created }}
        - name: Publish
          if: ${{ steps.release.outputs.release_created }}
          run: |
            git config user.name github-actions[bot]
            git config user.email spark-engine-web+githubactions@users.noreply.github.com
            git add -A
            git commit -m 'chore(release): ${{steps.release.outputs.tag_name}} [skip ci]\n'
            git tag -d v${{ steps.release.outputs.major }} || true
            git tag -d v${{ steps.release.outputs.major }}.${{ steps.release.outputs.minor }} || true
            git push origin :v${{ steps.release.outputs.major }} || true
            git push origin :v${{ steps.release.outputs.major }}.${{ steps.release.outputs.minor }} || true
            git tag -a v${{ steps.release.outputs.major }} -m "Release v${{ steps.release.outputs.major }}"
            git tag -a v${{ steps.release.outputs.major }}.${{ steps.release.outputs.minor }} -m "Release v${{ steps.release.outputs.major }}.${{ steps.release.outputs.minor }}"
            git push origin v${{ steps.release.outputs.major }}
            git push origin v${{ steps.release.outputs.major }}.${{ steps.release.outputs.minor }}
            gh release upload ${{ steps.release.outputs.tag_name }}
      needs: [test_unit, test_visual, build]
      if: github.ref_name == 'main'

        
        
